### ISSUE TITLE
[Demo] Demo-Repository als Template einstellen

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/D2G-Aufgaben-Demo#3]
Damit wechseln wir die Art, wie Kopien des Repositorys erstellt werden können (Aktuell: Forks). Wir haben den Vorteil, dass die Forks nicht mehr aufgelistet werden (Wenn viele dieses Repo forken, würde das sehr unübersichtlich werden), und gleichzeitig kann man damit aus öffentlichen Repos private Kopien erstellen (Datenschutz).

Nachteil: Keine gemeinsame History der Repos mehr, aktualisieren der "Forks" umständlicher (Bei Templates wird die Historie zu einem Commit zusammengemergt).

**Comment by AKirsch1** [comment]
@cagix Ich hatte das jetzt auch nur durch Zufall in den Einstellungen bei meinem Test-Repo gesehen.

> wenn ich von einem template-repo einen "fork" (kopie?) anlege, geht das nur im selben namespace oder könnte ein studi ein template aus der pm-organisation entsprechend nutzen?

Die können das in ihrem eigenen Namespace erstellen. Und im Gegensatz zu Forks auch als privates Repo, was für mich eindeutig ein Vorteil ist. (Nachteil: Ein Tutor/D2G-Account muss dann anderweitig für die Bewertung Zugriff auf das Repo erhalten)

> kannst du genauer sagen, wie das mit der history ist? habe ich wenigstens einen gemeinsamen commit (id), so dass ich später syncen kann bei bedarf?

Ich habe es nicht ausprobiert. Aber wenn ich es richtig verstanden habe, wird alles zu einem neuen Commit zusammengemergt im neuen Repo. Es gibt also keine gemeinsame Historie. Damit würde ein "syncen" vermutlich sehr umständlich werden.

**Comment by cagix** [comment]
> > kannst du genauer sagen, wie das mit der history ist? habe ich wenigstens einen gemeinsamen commit (id), so dass ich später syncen kann bei bedarf?
> 
> **Ich habe es nicht ausprobiert.** Aber wenn ich es richtig verstanden habe, wird alles zu einem neuen Commit zusammengemergt im neuen Repo. Es gibt also keine gemeinsame Historie. Damit würde ein "syncen" vermutlich sehr umständlich werden.

@AKirsch1 Das wäre aber genau das, was ich von einem WiMi erwarten würde :) ... Wenn Du noch genug Zeit hast, kannst Du das bitte einmal ausprobieren und schauen, was da passiert?

**Comment by AKirsch1** [comment]
@cagix Gerade ausgetestet. Wie geschrieben gibt es eine neue Commit-ID. Pullen/Mergen mit dem Template-Repo ist dann nicht mehr so einfach möglich. Was man dann machen kann, ist ein Pull mit der Option `--allow-unrelated-histories`. Das hat bei mir aber zu einem Merge-Konflikt geführt, d.h. alle Unterschiede zwischen den beiden Repos müssten dann wohl per Hand resolved werden. Bei kleinen Änderungen würde das gehen, aber ob das einem Studierenden zuzumuten ist?

**Comment by cagix** [comment]
> @cagix Gerade ausgetestet. Wie geschrieben gibt es eine neue Commit-ID. Pullen/Mergen mit dem Template-Repo ist dann nicht mehr so einfach möglich. Was man dann machen kann, ist ein Pull mit der Option `--allow-unrelated-histories`. Das hat bei mir aber zu einem Merge-Konflikt geführt, d.h. alle Unterschiede zwischen den beiden Repos müssten dann wohl per Hand resolved werden. Bei kleinen Änderungen würde das gehen, aber ob das einem Studierenden zuzumuten ist?

danke. 

die nächste frage wäre: ist die neue commit-id für alle "forks" identisch (sofern sie vom selben stand des template-repos abstammen)? 

aber vermutlich ist der template-mechanismus einfach nicht für kleinere änderungen zwischendurch gedacht. evtl. könnte man einen diff erzeugen und an die studis verteilen - angeblich arbeiten die linux-maintainer ja immer noch so?

**Comment by AKirsch1** [comment]
> die nächste frage wäre: ist die neue commit-id für alle "forks" identisch (sofern sie vom selben stand des template-repos abstammen)?

Ne, die ist bei jedem anders.

> aber vermutlich ist der template-mechanismus einfach nicht für kleinere änderungen zwischendurch gedacht

Die Frage ist doch auch, wie häufig wird es solche Zwischendurch-Änderungen geben. Eigentlich sollte sich die Aufgabenstellung ja nicht so häufig ändern. Abgesehen von irgendwelchen Fehlern in den Aufgabenstellungen.

**Comment by AKirsch1** [comment]
Ich würde dieses Issue hier erstmal schließen und wir bleiben erstmal bei Forks. Ich denke, dass man mal über einen längeren Zeitraum beides ausprobieren müsste, um eine sinnvolle Entscheidung treffen zu können.

@cagix Falls du anderer Meinung bist, kannst du das Issue wieder öffnen.

**Comment by cagix** [comment]
> Ich würde dieses Issue hier erstmal schließen und wir bleiben erstmal bei Forks. Ich denke, dass man mal über einen längeren Zeitraum beides ausprobieren müsste, um eine sinnvolle Entscheidung treffen zu können.
> 
> @cagix Falls du anderer Meinung bist, kannst du das Issue wieder öffnen.

@AKirsch1 naja, im prinzip finde ich die idee mit dem template statt fork super. nur müsste man halt irgendwie die frage nach dem aktualisieren beantwortet kriegen - die _wird_ sich definitiv stellen. 

wenn du jetzt keine stunden mehr hast, um hier aktiv zu werden, würde ich dich um ein "erinnerungs"-ticket bitten, welches hierhin verlinkt. titel könnte sein "Vorgabe-Repo als Template (statt forken)?".
